language: rust
sudo: false

# Since most OS-specific code has moved to the getrandom crate, we require
# few target-specific tests here.

matrix:
  include:
    # This target catches endianness issues
    - rust: stable
      sudo: required
      dist: trusty
      services: docker
      name: "Linux (MIPS, big-endian)"
      env: TARGET=mips-unknown-linux-gnu
      install:
        - sh utils/ci/install.sh
        - source ~/.cargo/env || true

    - rust: nightly
      name: "Linux, nightly (32-bit test)"
      env: TARGET=i686-unknown-linux-musl
      install:
        - rustup target add $TARGET
